//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conference_MediaPartners
    {
        public int Id { get; set; }
        public int FK_ConferenceId { get; set; }
        public string WebUrl { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string ImgSrc { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
    
        public virtual Conference Conference { get; set; }
    }
}
