//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public string Title { get; set; }
        public string ImageUrl { get; set; }
        public string Abstract { get; set; }
        public int FK_ConferenceId { get; set; }
        public System.DateTime ProgramDt { get; set; }
        public bool isPoster { get; set; }
    
        public virtual Conference Conference { get; set; }
    }
}
